### ISSUE TITLE
Error: Cannot find module './drivers/indexeddb'

### ISSUE THREAD

**Issue by Ouabi54** [frozeman/meteor-persistent-minimongo2#3]
Hello,

I try to use this package with ethereum  in my project but when i try to do an:
UsersObserver = new PersistentMinimongo2(Users); 

I have this error:
Error: Cannot find module './drivers/indexeddb'

I have find nothing about this on Google.

Have you a solution for this issues ?

**Comment by gitTerebi** [comment]
Use this package instead https://github.com/frozeman/meteor-persistent-minimongo
